/*
 Generated by typeshare 1.13.2
*/

export interface ApiTestRunSummary {
	testRunId: number;
	testRunDate: string;
	elapsedTime: string;
	totalTests: number;
	passedTests: number;
	failedTests: number;
	skippedTests: number;
	errorCount: number;
}

export interface ProjectOverviewResponse {
	id: number;
	name: string;
	createDate: string;
	testRunCount: number;
	lastTestRunSummary?: ApiTestRunSummary;
}

export interface ProjectResponse {
	id: number;
	name: string;
	createDate: string;
	testRunCount: number;
	testRunsSummaries: ApiTestRunSummary[];
}

