/*
 Generated by typeshare 1.13.2
*/

export interface TestRunSummary {
	testRunDate: string;
	totalTests: number;
	passedTests: number;
	failedTests: number;
	skippedTests: number;
}

export interface ProjectOverviewResponse {
	id: number;
	name: string;
	createDate: string;
	testRunCount: number;
	lastTestRunSummary?: TestRunSummary;
}

